# Generated by Django 2.1.7 on 2019-05-31 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=None, null=True, verbose_name='作成日')),
                ('no', models.IntegerField(default=0, verbose_name='大問')),
                ('sub_no', models.PositiveIntegerField(default=0, verbose_name='小問')),
                ('point', models.PositiveIntegerField(default=0, verbose_name='配点')),
                ('correct', models.CharField(blank=True, choices=[('MARK1', 'Mark 1'), ('MARK2', 'Mark 2'), ('MARK3', 'Mark 3'), ('MARK4', 'Mark 4'), ('MARK5', 'Mark 5')], max_length=30)),
            ],
            options={
                'verbose_name': '解答',
                'verbose_name_plural': '解答',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, verbose_name='ドリルの説明')),
                ('created', models.DateTimeField(blank=True, default=None, verbose_name='作成日')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='テスト名')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('number_of_question', models.IntegerField(default=1, verbose_name='問題数')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '試験',
                'verbose_name_plural': '試験',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('point', models.PositiveIntegerField(blank=True)),
                ('created', models.DateTimeField(blank=True, default=None)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('your_choice', models.CharField(blank=True, choices=[('MARK1', 'Mark 1'), ('MARK2', 'Mark 2'), ('MARK3', 'Mark 3'), ('MARK4', 'Mark 4'), ('MARK5', 'Mark 5')], max_length=30)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice.Answer')),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice.Drill')),
            ],
        ),
        migrations.AddField(
            model_name='drill',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice.Exam'),
        ),
        migrations.AddField(
            model_name='answer',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice.Exam'),
        ),
    ]
