# Generated by Django 2.1.7 on 2019-06-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['no', 'sub_no'], 'verbose_name': '解答', 'verbose_name_plural': '解答'},
        ),
        migrations.AlterField(
            model_name='drill',
            name='created',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='作成日'),
        ),
    ]
