# Generated by Django 2.1.7 on 2019-06-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0002_auto_20190603_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='created_date',
            new_name='created',
        ),
    ]
