# Generated by Django 2.1.7 on 2019-02-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0002_auto_20190215_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mychoice',
            old_name='Exam',
            new_name='exam',
        ),
        migrations.AddField(
            model_name='mychoice',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
