# Generated by Django 2.1.7 on 2019-02-19 20:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0002_question_my_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='my_field2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item title 2.1'), (2, 'Item title 2.2'), (3, 'Item title 2.3'), (4, 'Item title 2.4'), (5, 'Item title 2.5')], max_length=3),
        ),
    ]
