# Generated by Django 2.1.7 on 2019-02-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0003_auto_20190215_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='mychoice',
            name='sub_no',
            field=models.IntegerField(default=0),
        ),
    ]
