# Generated by Django 2.1.7 on 2019-03-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0004_auto_20190222_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice1',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice2',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice3',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice4',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice5',
            field=models.BooleanField(null=True),
        ),
    ]
