# Generated by Django 2.1.7 on 2019-03-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0005_auto_20190311_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice5',
            field=models.BooleanField(default=False),
        ),
    ]
