# Generated by Django 2.1.7 on 2019-03-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0006_auto_20190311_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice5',
        ),
    ]
