# Generated by Django 2.1.7 on 2019-03-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0008_auto_20190311_2045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='my_choice',
        ),
    ]
