# Generated by Django 2.1.7 on 2019-03-23 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0009_auto_20190313_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['pk'], 'verbose_name': '試験', 'verbose_name_plural': '試験'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['pk'], 'verbose_name': '問題', 'verbose_name_plural': '問題'},
        ),
        migrations.AddField(
            model_name='exam',
            name='number_of_question',
            field=models.IntegerField(default=1, verbose_name='問題数'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=200, verbose_name='テスト名'),
        ),
        migrations.AlterField(
            model_name='question',
            name='no',
            field=models.IntegerField(default=0, verbose_name='大問'),
        ),
        migrations.AlterField(
            model_name='question',
            name='point',
            field=models.IntegerField(default=0, verbose_name='配点'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sub_no',
            field=models.IntegerField(default=0, verbose_name='小問'),
        ),
    ]
