# Generated by Django 2.1.7 on 2019-04-10 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0011_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('src', models.FileField(upload_to='', verbose_name='添付ファイル')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='choice.Bookmark', verbose_name='紐づく記事')),
            ],
        ),
    ]
