# Generated by Django 2.1.7 on 2019-04-20 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0012_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='target',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
