# Generated by Django 2.1.7 on 2019-05-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0014_auto_20190430_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice5',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.PositiveIntegerField(default=1, verbose_name='正解'),
        ),
    ]
