# Generated by Django 2.1.7 on 2019-05-09 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0017_auto_20190506_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.PositiveIntegerField(default=1)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='テスト名')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice.Exam')),
            ],
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='correct_answer',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='answer',
            name='quesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice.Question'),
        ),
    ]
