# Generated by Django 2.1.7 on 2019-05-09 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0019_auto_20190509_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='drill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice.Drill'),
        ),
    ]
