# Generated by Django 2.1.7 on 2019-05-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0020_auto_20190509_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
