# Generated by Django 2.1.7 on 2019-05-11 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0021_auto_20190511_1255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='CorrectAns',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='correctans',
        ),
    ]
