# Generated by Django 2.1.7 on 2019-05-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0022_auto_20190511_1326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Mark',
        ),
    ]
