# Generated by Django 2.1.7 on 2019-05-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0024_mark_your_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctans',
            name='answer',
            field=models.CharField(blank=True, choices=[('MARK1', 'Mark 1'), ('MARK2', 'Mark 2'), ('MARK3', 'Mark 3'), ('MARK4', 'Mark 4'), ('MARK5', 'Mark 5')], max_length=30),
        ),
    ]
