# Generated by Django 2.1.7 on 2019-05-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0026_remove_correctans_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='your_choice',
        ),
    ]
