# Generated by Django 2.1.7 on 2019-05-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0028_mark_your_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='your_choice',
        ),
    ]
