# Generated by Django 2.1.7 on 2019-05-18 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0030_mark_your_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='your_choice',
            new_name='pretty',
        ),
    ]
