# Generated by Django 2.1.7 on 2019-05-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0031_auto_20190518_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='pretty',
        ),
    ]
