# Generated by Django 2.1.7 on 2019-05-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0033_mark_pretty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='pretty',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
