# Generated by Django 2.1.7 on 2019-05-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0034_auto_20190518_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='pretty',
        ),
        migrations.AddField(
            model_name='mark',
            name='your_choice',
            field=models.CharField(blank=True, choices=[('MARK1', 'Mark 1'), ('MARK2', 'Mark 2'), ('MARK3', 'Mark 3'), ('MARK4', 'Mark 4'), ('MARK5', 'Mark 5')], max_length=30),
        ),
    ]
