# Generated by Django 2.1.7 on 2019-05-18 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0036_correctans_c_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctans',
            name='c_answer',
        ),
    ]
