# Generated by Django 2.1.7 on 2019-05-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0039_remove_mark_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctans',
            name='correct_answer',
        ),
    ]
