# Generated by Django 2.1.7 on 2019-05-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0040_remove_correctans_correct_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correctans',
            old_name='c_answer',
            new_name='answer',
        ),
    ]
