# Generated by Django 2.1.7 on 2019-05-22 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0041_auto_20190518_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(blank=True)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice.Drill')),
            ],
        ),
    ]
