# Generated by Django 2.1.7 on 2019-05-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0042_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='created',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
