# Generated by Django 2.1.7 on 2019-05-22 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0043_grade_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='drill',
        ),
        migrations.AddField(
            model_name='grade',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='choice.Exam'),
            preserve_default=False,
        ),
    ]
