# Generated by Django 2.1.7 on 2019-05-24 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0044_auto_20190522_2221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CorrectAns',
            new_name='Answer',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='correct',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='correctans',
            new_name='answer',
        ),
    ]
