# Generated by Django 2.1.7 on 2019-05-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0045_auto_20190524_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drill',
            old_name='title',
            new_name='description',
        ),
        migrations.AddField(
            model_name='drill',
            name='created',
            field=models.DateTimeField(blank=True, default=None, verbose_name='作成日'),
        ),
    ]
