# Generated by Django 2.1.7 on 2019-05-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0046_auto_20190526_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(blank=True, default=None, verbose_name='作成日'),
        ),
    ]
