# Generated by Django 2.1.7 on 2019-05-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0047_answer_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='作成日'),
        ),
    ]
