# Generated by Django 2.1.7 on 2019-05-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0048_auto_20190526_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['pk'], 'verbose_name': '解答', 'verbose_name_plural': '解答'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='point',
            field=models.PositiveIntegerField(default=0, verbose_name='配点'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='sub_no',
            field=models.PositiveIntegerField(default=0, verbose_name='小問'),
        ),
        migrations.AlterField(
            model_name='drill',
            name='description',
            field=models.CharField(max_length=200, verbose_name='ドリルの説明'),
        ),
    ]
