# Generated by Django 2.1.7 on 2019-06-08 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0003_auto_20190603_0504'),
        ('choice', '0049_auto_20190526_2315'),
    ]

    operations = [
    ]
