# Generated by Django 2.2.2 on 2019-06-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0050_merge_20190609_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('publications', models.ManyToManyField(to='choice.Publication')),
            ],
            options={
                'ordering': ('headline',),
            },
        ),
    ]
